const $=id=>document.getElementById(id);const video=$('video'),canvas=$('world'),ctx=canvas.getContext('2d');let stream=null,url=null,worker=null,report=null,running=false;
function status(t){$('status').textContent=t}
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function drawWorld(t=0){resize();const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle='#05070b';ctx.fillRect(0,0,w,h);const n=report?Math.min(2400,Math.max(700,report.points)):1000,phase=t*((report?.motion||1)+.5);for(let i=0;i<n;i++){const a=i*2.399+phase*.12,r=25+(i%n)*(Math.min(w,h)*.45/n),z=.45+.55*Math.sin(a*2+phase),x=w/2+Math.cos(a+phase)*r,y=h/2+Math.sin(a*1.31+phase*.7)*r*.55;ctx.globalAlpha=.18+.72*z;ctx.fillStyle=i%5===0?'#fbbf24':i%3===0?'#a78bfa':'#67e8f9';ctx.fillRect(x,y,1.5+2*z,1.5+2*z)}ctx.globalAlpha=1}
function reportDone(r){report=r;$('stats').innerHTML=[['Muestras',r.samples],['Cambios',r.events],['Movimiento',r.motion.toFixed(2)],['Profundidad/estructura',r.edge.toFixed(2)],['Puntos 4D',r.points]].map(x=>'<div class="stat"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('');$('events').textContent='Campo 4D generado · '+r.samples+' instantes fusionados';drawWorld(video.currentTime||0)}
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});video.srcObject=stream;await video.play();video.onloadedmetadata=()=>{$('run').disabled=false;status('Cámara en vivo · sensores visuales activos');drawWorld()}}catch(e){status('No se pudo acceder a la cámara: '+e.message)}}
$('live').onclick=startCamera;
$('videoFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(url)URL.revokeObjectURL(url);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}url=URL.createObjectURL(f);video.srcObject=null;video.src=url;video.onloadedmetadata=()=>{$('run').disabled=false;$('time').max=video.duration;status('Video anterior cargado · '+video.duration.toFixed(2)+' s');drawWorld()}};
$('run').onclick=async()=>{if(!video.videoWidth)return;running=true;status('Construyendo mundo 4D con todos los datos disponibles…');worker??=new Worker('./imagen4d_worker.js');worker.onmessage=e=>{if(e.data.type==='progress')status('Fusionando '+e.data.i+'/'+e.data.total+' instantes…');if(e.data.type==='done'){reportDone(e.data.report);status('Mundo 4D generado')}};const W=192,H=Math.max(108,Math.round(192*video.videoHeight/video.videoWidth)),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d',{willReadFrequently:true}),duration=video.duration||60,frames=Math.min(90,Math.max(24,Math.ceil(duration*3))),samples=[];for(let i=0;i<frames;i++){if(!video.srcObject){video.currentTime=duration*i/(frames-1||1);await new Promise(r=>video.onseeked=r)}else await new Promise(r=>setTimeout(r,50));x.drawImage(video,0,0,W,H);samples.push(x.getImageData(0,0,W,H).data.buffer)}const sensors=samples.map((_,i)=>({t:duration*i/(frames-1||1),rssi:-70,type:'available'}));worker.postMessage({type:'analyze',frames,sensors,width:W,height:H,duration},samples)};
$('play').onclick=()=>video.paused?video.play():video.pause();video.ontimeupdate=()=>{if(video.duration){$('time').value=video.currentTime;$('clock').textContent=video.currentTime.toFixed(1)+' / '+video.duration.toFixed(1)+' s'}drawWorld(video.currentTime)};$('time').oninput=e=>{if(!video.srcObject)video.currentTime=+e.target.value;drawWorld(+e.target.value)};window.onresize=()=>drawWorld(video.currentTime);
