const $=id=>document.getElementById(id);const video=$('video'),canvas=$('world'),ctx=canvas.getContext('2d');let url=null,worker=null,report=null,sensorData=null;

function status(t){$('status').textContent=t}
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function sensorAt(t){if(!sensorData?.length)return null;let best=sensorData[0],bd=Math.abs(best.t-t);for(const s of sensorData){const d=Math.abs(s.t-t);if(d<bd){best=s;bd=d}}return best}
function drawWorld(t=0){resize();const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle='#05070b';ctx.fillRect(0,0,w,h);if(!report)return;
 const n=Math.min(2200,Math.max(500,report.points)),phase=t*(report.motion+.5),s=sensorAt(t);
 const echoStrength=s?Math.min(1,Math.max(0,(Math.abs(s.rssi)+20)/90)):0.35;
 const cx=w/2+(s?.x||0)*w*.28,cy=h/2+(s?.y||0)*h*.22;
 for(let i=0;i<n;i++){const a=i*2.399+phase*.12,r=28+(i%n)*(Math.min(w,h)*.44/n),wave=1+echoStrength*24*Math.sin(r*.055-phase*3);const x=cx+Math.cos(a+phase)*r*wave*.025,y=cy+Math.sin(a*1.31+phase*.7)*r*.55;const z=.45+.55*Math.sin(a*2+phase);ctx.globalAlpha=.2+.7*z;ctx.fillStyle=i%7===0?'#fbbf24':(i%3===0?'#a78bfa':'#67e8f9');ctx.fillRect(x,y,1.5+2*z,1.5+2*z)}
 ctx.globalAlpha=.22;ctx.beginPath();ctx.arc(cx,cy,35+echoStrength*110,0,Math.PI*2);ctx.strokeStyle='#fbbf24';ctx.stroke();ctx.globalAlpha=1}

function renderReport(r){report=r;$('stats').innerHTML=[['Muestras',r.samples],['Cambios',r.events],['Movimiento',r.motion.toFixed(2)],['Bordes',r.edge.toFixed(2)],['Escena base',r.baseScore.toFixed(2)],['Puntos 4D',r.points],['Fuentes radio',r.sensorSources]].map(x=>'<div class="stat"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('');
 $('events').innerHTML=r.timeline.length?r.timeline.map(e=>'<div class="event"><span><b>'+e.t.toFixed(2)+'s</b> · '+e.type+'</span><span>'+e.score.toFixed(2)+'</span></div>').join(''):'Sin cambios relevantes';drawWorld()}
$('videoFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.src=url;video.onloadedmetadata=()=>{$('run').disabled=false;$('time').max=video.duration;status('Video cargado · '+video.duration.toFixed(2)+' s');drawWorld()}});
$('sensorFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const raw=await f.text();let rows;if(f.name.endsWith('.json'))rows=JSON.parse(raw);else{const lines=raw.trim().split(/\\r?\\n/);const head=lines.shift().split(',');rows=lines.map(l=>{const v=l.split(',');return Object.fromEntries(head.map((k,i)=>[k.trim(),v[i]]))})}sensorData=(Array.isArray(rows)?rows:rows.samples||rows.data||[]).map((s,i)=>({t:+s.t||+s.timestamp||i,rssi:+s.rssi||-70,x:+s.x||0,y:+s.y||0,z:+s.z||0,type:s.type||s.sourceType||'radio'})).sort((a,b)=>a.t-b.t);$('sensorStatus').textContent='Eco cargado · '+sensorData.length+' observaciones · Wi‑Fi/Bluetooth listo para fusionar';drawWorld(video.currentTime||0)}catch(err){$('sensorStatus').textContent='No se pudo leer el archivo de sensores.'}});
$('run').addEventListener('click',async()=>{if(!video.duration)return;status('Extrayendo muestras y fusionando cámara + sensores…');worker??=new Worker('./imagen4d_worker.js');worker.onmessage=e=>{if(e.data.type==='progress')status('Analizando '+e.data.i+'/'+e.data.total+' muestras…');if(e.data.type==='done'){renderReport(e.data.report);status('Mundo 4D generado · cámara + eco + tiempo')}};const W=192,H=Math.max(108,Math.round(192*video.videoHeight/video.videoWidth)),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d',{willReadFrequently:true});const frames=Math.min(60,Math.max(12,Math.ceil(video.duration*4))),samples=[];for(let i=0;i<frames;i++){video.currentTime=video.duration*i/(frames-1||1);await new Promise(r=>video.onseeked=r);x.drawImage(video,0,0,W,H);samples.push(x.getImageData(0,0,W,H).data.buffer)}const sensors=sensorData||samples.map((_,i)=>({t:video.duration*i/(frames-1||1),rssi:-72+18*Math.sin(i*.71),x:.25*Math.sin(i*.33),y:.18*Math.cos(i*.27),type:'simulated'}));worker.postMessage({type:'analyze',frames:samples,width:W,height:H,duration:video.duration,sensors},samples)});
$('play').onclick=()=>{if(video.paused)video.play();else video.pause()};video.addEventListener('timeupdate',()=>{$('time').value=video.currentTime;$('clock').textContent=video.currentTime.toFixed(1)+' / '+video.duration.toFixed(1)+' s';drawWorld(video.currentTime)});$('time').oninput=e=>{video.currentTime=+e.target.value;drawWorld(video.currentTime)};window.onresize=()=>drawWorld(video.currentTime);
